### ISSUE TITLE
Bug Report: “Command Failed to send.”

### ISSUE THREAD

**Issue by Octoboy457** [Undertale-RPG/Undertale-RPG#11]
### What Feature do you want to report a bug for?

Whenever I try to use the bot, it fails to send it.

### Detailed description of the bug you wish to report?

Whenever I try to use the bot, wether it be to fight or check stats or use booster, it ends up taking a long moment to try and send the command, and then fails.  I’m not sure if it’s because if I’m in poor WiFi or if it’s an issue with the bot itself, but I am not having a good time.

### terms & Privicy

- [x] by checking this box you agree to our [Terms of Service](https://undertalerpg.monster/terms) and [Privicy Policy](https://undertalerpg.monster/privacy)

**Comment by LetsChill** [comment]
Hello @Octoboy457 

We are sorry to hear your struggles, This issue happens whenever the bot shuts down or an error happens within the bot.

If you get into the same issue in the future, you can wait for 30 to one hour and recheck if the bot will respond or not.

We hope you have fun playing with Undertale-RPG!

**Comment by LetsChill** [comment]
Hello @Octoboy457 

We are sorry to hear your struggles, This issue happens whenever the bot shuts down or an error happens within the bot.

If you get into the same issue in the future, you can wait for 30 to one hour and recheck if the bot will respond or not.

We hope you have fun playing with Undertale-RPG!
