### ISSUE TITLE
Bug Report: It won't let me add to server

### ISSUE THREAD

**Issue by zeldaking** [Undertale-RPG/Undertale-RPG#14]
### What Feature do you want to report a bug for?

It wont let me add it to server

### Detailed description of the bug you wish to report?

![9D7646F0-B90C-459E-BB2B-3A2A5A2AB3B5](https://user-images.githubusercontent.com/43257330/189502396-a8ba7f1a-ebff-440e-a95c-c033c9d74f04.jpeg)
Here's the image of what happens

### terms & Privicy

- [X] by checking this box you agree to our [Terms of Service](https://undertalerpg.monster/terms) and [Privicy Policy](https://undertalerpg.monster/privacy)

**Comment by yakirarage** [comment]
As the screenshot says it us waiting for verification for a feature so the bot can work properly

**Comment by zeldaking** [comment]
Can the dev fix it? Or is it something I have to do?

**Comment by yakirarage** [comment]
> Can the dev fix it? Or is it something I have to do?

I am the dev and as i said we are waiting for verification for a specific feature so the bot can work properly its just the waiting game its not a bug
