### ISSUE TITLE
Bug Report: The application did not respond Glitch

### ISSUE THREAD

**Issue by TheFox12345** [Undertale-RPG/Undertale-RPG#15]
### What Feature do you want to report a bug for?

Undertale RPG Bot

### Detailed description of the bug you wish to report?

Me do command, bot respond with "The application did not respond"

### terms & Privicy

- [X] by checking this box you agree to our [Terms of Service](https://undertalerpg.monster/terms) and [Privicy Policy](https://undertalerpg.monster/privacy)

**Comment by yakirarage** [comment]
did anyone delete one of your earlier fight/shop messages?

**Comment by TheFox12345** [comment]
> did anyone delete one of your earlier fight/shop messages?

Nope

**Comment by TheFox12345** [comment]
> did anyone delete one of your earlier fight/shop messages?

I did close a boss fight tho

**Comment by yakirarage** [comment]
> > did anyone delete one of your earlier fight/shop messages?
> 
> Nope

then please explain what happened, what command did you do did you have any bugs with a earlier fight like it closing to early etc

**Comment by TheFox12345** [comment]
> > > did anyone delete one of your earlier fight/shop messages?
> > 
> > 
> > Nope
> 
> then please explain what happened, what command did you do did you have any bugs with a earlier fight like it closing to early etc

/boss delete /boss and yeah i was just testing

**Comment by yakirarage** [comment]
if you didnt close the first correctly it will do that i am already working on a fix but ty for letting me know 

next time do not delete the bots messages without a good reason (it will make bugs worse or creates bugs)

**Comment by TheFox12345** [comment]
> if you didnt close the first correctly it will do that i am already working on a fix but ty for letting me know
> 
> next time do not delete the bots messages without a good reason (it will make bugs worse or creates bugs)

alr i wont
