### ISSUE TITLE
Bug Report: Unable to see my stats

### ISSUE THREAD

**Issue by Kaidojet** [Undertale-RPG/Undertale-RPG#16]
### What Feature do you want to report a bug for?

Stats command

### Detailed description of the bug you wish to report?

Idk why but I can't see my stats...I tried in different servers to see if it was only one not working but every server got the same result
![Screenshot_2022-09-28-17-03-41-33_572064f74bd5f9fa804b05334aa4f912](https://user-images.githubusercontent.com/114597489/192814866-19336116-bf09-4580-a76a-c5a47a52340c.jpg) 
But when I try to stats someone that never played in UT RPG i can see their stats thing that is pretty strange- 
![Screenshot_2022-09-28-17-03-58-18_572064f74bd5f9fa804b05334aa4f912](https://user-images.githubusercontent.com/114597489/192815445-b5572f11-82ae-4453-bfe0-70307a5488ba.jpg)
 And yes I can't stats other players that already played before 

### terms & Privicy

- [x] by checking this box you agree to our [Terms of Service](https://undertalerpg.monster/terms) and [Privicy Policy](https://undertalerpg.monster/privacy)

**Comment by LetsChill** [comment]
Thank you for your report, We have investigated the issue and it was resolved,

Have fun playing with Undertale-RPG!
