### ISSUE TITLE
Hp changed?

### ISSUE THREAD

**Issue by Seantrooper100** [Undertale-RPG/Undertale-RPG#18]
### What Feature do you want to report a bug for?

Item usage and Hp

### Detailed description of the bug you wish to report?

So I was in the toriel boss fight cause of the requirements to beat her to go to snowdin. I used an item then suddenly my hp changed. I hope I didn't lose progress but now I have to figure out how to restore my hp
![Screenshot_20221008-115239_Discord](https://user-images.githubusercontent.com/115370900/194722744-2ecf08a8-2791-4dd5-9aa9-96c650920668.jpg)`

### terms & Privicy

- [X] by checking this box you agree to our [Terms of Service](https://undertalerpg.monster/terms) and [Privicy Policy](https://undertalerpg.monster/privacy)

**Comment by yakirarage** [comment]
this is not a bug.
