### ISSUE TITLE
/fight bug

### ISSUE THREAD

**Issue by Romansblack** [Undertale-RPG/Undertale-RPG#20]
### What Feature do you want to report a bug for?

/fight 

### Detailed description of the bug you wish to report?

So as you know, sometimes when you fight, the options don't load, and the bot still thinks your in the battle.
But I have found out it's for clicking on an option too fast, something in it's coding might be broken, can you fix this?

### terms & Privicy

- [X] by checking this box you agree to our [Terms of Service](https://undertalerpg.monster/terms) and [Privicy Policy](https://undertalerpg.monster/privacy)

### Additional comments

Na

**Comment by Romansblack** [comment]
Go

**Comment by yakirarage** [comment]
you will have to explain better what exactly it is that you think needs to change or is wrong

**Comment by Romansblack** [comment]
It's mainly how that sometimes,(most of the time) when you click fight, items, or mercy, the bot doesn't progress to you doing damage to the monster/boss, basically locking you out of the whole bot until you either restart the bot completely, or reinstall discord.(at least for me)

Y'all probably have to rework some of the bot, specifically for fighting, since of course this is a active bug

**Comment by yakirarage** [comment]
it is indeed a bug (the part of being locked down to the bot) how ever it does not work the way you think it does i am already working on a fix as i know what the issue is how ever this may take some time so please be patient

the bot gets a daily restart everyday at midnight European time (CET timezone) i dont know if reinstalling your discord would matter or if that is just by luck

**Comment by Romansblack** [comment]
So basically, as I said, when you pick fight, items, or mercy, as you pick one of them, the bot doesn't load you doing damage to the monster/boss, effectively locking you out of anything until the daily fix, or reinstalling discord.

This has been a active bug, as you know, so I believe it has something to do with the bot not processing the options correctly, so I recommend y'all to find the piece of code thats causing it, and rework that bit, since I cant look at the code myself

**Comment by Romansblack** [comment]
> it is indeed a bug (the part of being locked down to the bot) how ever it does not work the way you think it does i am already working on a fix as i know what the issue is how ever this may take some time so please be patient
> 
> the bot gets a daily restart everyday at midnight European time (CET timezone) i dont know if reinstalling your discord would matter or if that is just by luck

Thank you for the information

**Comment by Romansblack** [comment]
Don't read the comment above

**Comment by yakirarage** [comment]
also you may look at the code if you feel like it just click on the tab called code next to the tab saying issues
