### ISSUE TITLE
PLEASE HELP

### ISSUE THREAD

**Issue by asriel1232** [Undertale-RPG/Undertale-RPG#26]
### What Feature do you want to report a bug for?

BOT

### Detailed description of the bug you wish to report?

I FIGHTED HIM AND HE DONT SHOW BUTTONS AND NOW HE ONLY CAN SAY APPLICATION NOT RESPONDED!!!!

### terms & Privicy

- [X] by checking this box you agree to our [Terms of Service](https://undertalerpg.monster/terms) and [Privicy Policy](https://undertalerpg.monster/privacy)

### Additional comments

PLZ HELP ASAP

**Comment by yakirarage** [comment]
this is a duplicated report please add any additional info to the original report 


**stop treating me as your slave i work on the bot when i have time so it will be fixed when it gets fixed**
