### ISSUE TITLE
2x crates with 1 crate

### ISSUE THREAD

**Issue by ChatXGitHub** [Undertale-RPG/Undertale-RPG#9]
Basically opening multiple crates when you only have 1 

I just voted, decided to open a crate and right when it was "Opening a crate..." I /open and re opened that same crate since the number didn't go down, and it worked 

**To Reproduce**
1. Do /vote, vote to get a crate
2. Do /open to open the crate and open it
3. While it's opening, simply /open and open that same crate since the number of crates was the same,
4. profit 2x the same crate

**Expected behavior**
I expected to give me 2x Gold though **I'm not sure if it's a visual glitch or if it actually worked**

**Screenshots**

**Additional context**
None

**Comment by yakirarage** [comment]
fixed with next update.
